### PR TITLE
feature(sqlx): add integration with sqlx

### PR DESCRIPTION
**Pull request by hxzhao527**
I'm not sure whether this is the proper way to integrate with sqlx.

In my opinion, implement ```sql.DB``` or ```sqlx.DB``` interface maybe more elegant. :joy: 
but that will change the whole project.

### CODE REVIEW

**Comment by hxzhao527** [comment]
not good enough, I will find a better way to implement this.

**Comment by davehowell** [comment]
I like that dotsql is a fairly simple wrapper over database/sql, and this PR looks the same over `sqlx`. It would be great to merge this in the meantime, and get access to useful things like the `Select` and easy prepared statements,  even if you want to spend time doing something to switch out `sql.DB` or `sqlx.DB` later.

**Comment by gchaincl** [comment]
I like it as well.
@hxzhao527 what would you change to make it _good enough_?

**Comment by hxzhao527** [comment]
:joy:  emmm, so sorry, I forgot what I want.

**Pull request closed without merging**
