### PR TITLE
Go modules support and missing unit tests

### PR DESCRIPTION
**Pull request by swithek**
This PR adds go modules support and missing unit tests, ~~completely removes integration tests~~. I think it would be appropriate, after merging this branch into master, to tag the latest commit as v1.0.0

### CODE REVIEW

**Comment by swithek** [comment]
Since the unit tests fully cover all aspects of dotsql by utilizing a mocked db layer, it is redundant to try to cover the same parts of code with integration tests whose only difference is real db usage instead of a mocked one. In this case, tests are not only slower, but they also introduce an unnecessary dependency (sqllite).

**Comment by gchaincl** [comment]
I see your point, but I still do think that testing against a real database gives you more confidence than mocks

**Comment by gchaincl** [comment]
Additionally, the fact that they run "slow" shouldn't be a problem cause they by default they don't run, unless you `tags=integration`

**Comment by swithek** [comment]
Extra layer of testing sounds reasonable, though I feel that integration tests wouldn't add any benefit mostly because neither the input (SQL queries) nor the execution (db implementation / driver) are influenced in any way by dotsql, we only need to ensure that those queries are delivered correctly to the db and that is easily checked via mocks.

**Comment by swithek** [comment]
But, of course, having those tests doesn't hurt nobody (sqlite will only be added as a dependency to go.mod and the less dependencies the better), so I could return integration tests if need be.

**Comment by swithek** [comment]
I modified the commits of this branch to preserve the integration tests. Everything else is the same.

**Pull request merged**
